apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx  # 注意：这里必须和 kubectl get po --show-labels 里的标签对应
  ports:
    - protocol: TCP
      port: 80        # Service 暴露的端口
      targetPort: 80  # Pod 内部 Nginx 监听的端口